{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Product Index\",\"Dynamic Calendar\",\"DimReplacement Cost\",\"Rolling Calendar Config\",\"Product Cost Index Transformed\",\"SP Connection - Material Mapping\",\"Material Mapping\",\"Material Code Config\",\"Inventory Reference\",\"Inventory Production Config\",\"SP Connection - 2023 Retail & Replacement Cost (Temporary)\",\"SP Connection - Data\",\"SP Connection - Inventory Reference\",\"2023 Retail & Replacement Cost (Temporary)\",\"SQL Connection - Master Material Data\",\"Parameter1\",\"Transform Sample File\",\"Sample File\",\"Transform File\",\"Parameter2\",\"Transform Sample File (2)\",\"Sample File (2)\",\"Transform File (2)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0 (24.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"CalcGroup\",\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "expressions": [
      {
        "name": "SP Connection - Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = SharePoint.Files(\"https://phccac.sharepoint.com/sites/MIS-UATBIandSolutioning/\", [ApiVersion = 15]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(Source,{\"Folder Path\", \"Content\", \"Name\", \"Extension\", \"Date accessed\", \"Date modified\", \"Date created\", \"Attributes\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Reordered Columns\", each ([Folder Path] = \"https://phccac.sharepoint.com/sites/MIS-UATBIandSolutioning/Shared Documents/FACTORY FINANCE UAT/PRODUCT COST INDEX/ZCOR001 Raw/\")),",
          "    #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),",
          "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File (2)\", each #\"Transform File (2)\"([Content])),",
          "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Invoke Custom Function1\", {\"Transform File (2)\"}),",
          "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (2)\", Table.ColumnNames(#\"Transform File (2)\"(#\"Sample File (2)\"))),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Costing Variant\", type text}, {\"Valuation area\", Int64.Type}, {\"FG Item Code\", Int64.Type}, {\"FG Item Code Description\", type text}, {\"Item Category\", type text}, {\"Cost Estimate Number\", Int64.Type}, {\"Item Code\", type text}, {\"Item Code Description\", type text}, {\"Costing Date\", Int64.Type}, {\"Cost Element\", Int64.Type}, {\"G/L Acct Long Text\", type text}, {\"TOTAL\", type number}, {\"QTY\", type number}, {\"UOM SAP\", type text}, {\"REPL Code\", Int64.Type}, {\"REPL Code Description\", type text}, {\"BOM Usage\", Int64.Type}, {\"Alternative BOM\", Int64.Type}, {\"Item (SD)\", Int64.Type}, {\"Main Plant\", Int64.Type}, {\"REPL Qty\", type number}, {\"REPL UOM\", type text}, {\"Vendor\", Int64.Type}, {\"Vendor Name\", type text}, {\"Comp Denom\", Int64.Type}, {\"Converted Base Qty\", type number}, {\"Base Unit of Measure\", type text}, {\"REPL Price\", type number}, {\"REPL Currency\", type text}, {\"PIR Price per UOM\", Int64.Type}, {\"Order Price Unit\", type text}, {\"PIR Denom\", Int64.Type}, {\"PIR Counter\", Int64.Type}, {\"PIR Base Net Price\", type number}, {\"Component Price\", type number}, {\"FX / FOREX\", type number}, {\"REPL FOB in PHP\", type number}, {\"ZFRF\", type number}, {\"ZDTX\", Int64.Type}, {\"ZOTH\", Int64.Type}, {\"ZBRO\", Int64.Type}, {\"ZINS\", Int64.Type}, {\"REPL LCF Rate\", Percentage.Type}, {\"REPL LCF Amount\", type number}, {\"REPL Total\", type number}, {\"Standard price\", type number}, {\"Standard Usage\", type number}, {\"Usage Variance\", type number}, {\"Material Group\", Int64.Type}, {\"Material Group Desc\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "eac3075c-7be7-4261-bae9-6b36a04d319a",
        "queryGroup": "Source Point"
      },
      {
        "name": "Dynamic Calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = {Number.From(#date(2024,01,01))..Number.From(#date(2024,12,31))},",
          "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"Date\"}}),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Date\", type date}}),",
          "    #\"Inserted Month Name\" = Table.AddColumn(#\"Changed Type\", \"Month\", each Date.MonthName([Date]), type text),",
          "    #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted Month Name\", \"Quarter\", each Date.QuarterOfYear([Date]), Int64.Type),",
          "    #\"Inserted Week of Year\" = Table.AddColumn(#\"Inserted Quarter\", \"Week of Year\", each Date.WeekOfYear([Date],1), Int64.Type),",
          "    #\"Subtracted from Column\" = Table.TransformColumns(#\"Inserted Week of Year\", {{\"Week of Year\", each _ -1, type number}}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Subtracted from Column\",0,52,Replacer.ReplaceValue,{\"Week of Year\"}),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value\",{\"Week of Year\"}),",
          "    #\"Inserted Year\" = Table.AddColumn(#\"Removed Columns\", \"Year\", each Date.Year([Date]), Int64.Type),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Inserted Year\",{{\"Year\", type text}}),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Changed Type1\",{\"Date\", \"Month\", \"Year\", \"Quarter\"}),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Reordered Columns\", \"Month-Year\", each [Month]&\" - \"&[Year]),",
          "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"Week-Year\", each \"Q\"&Number.ToText([Quarter])&\" - \"&[Year]),",
          "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Week-Year\", type text}}),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Changed Type2\",{{\"Week-Year\", \"Quarter Year\"}}),",
          "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"Year\", Int64.Type}}),",
          "    #\"Inserted CurrentThursday\" = Table.AddColumn(#\"Changed Type3\", \"CurrentThursday\", each Date.AddDays( [Date], 3 - Date.DayOfWeek([Date], Day.Monday)), type date),",
          "    #\"Inserted YearCurrentThursday\" = Table.AddColumn(#\"Inserted CurrentThursday\", \"YearCurrentThursday\", each Date.Year([CurrentThursday]), Int64.Type),",
          "    #\"Inserted FirstThursdayOfYear\" = Table.AddColumn(#\"Inserted YearCurrentThursday\", \"FirstThursdayOfYear\", each Date.AddDays( #date( [YearCurrentThursday],1 ,7 ), - Date.DayOfWeek( #date( [YearCurrentThursday],1 ,1), Day.Friday)), type date),",
          "    #\"Instered ISOWeek\" = Table.AddColumn(#\"Inserted FirstThursdayOfYear\", \"ISO WEEK\", each(Duration.Days( [CurrentThursday] - [FirstThursdayOfYear]) / 7) + 1, Int64.Type),",
          "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Instered ISOWeek\",{\"ISO WEEK\", \"Month\", \"Quarter\", \"Year\", \"Date\", \"Month-Year\", \"Quarter Year\", \"CurrentThursday\", \"YearCurrentThursday\", \"FirstThursdayOfYear\"}),",
          "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Reordered Columns1\",{{\"Date\", type date}})",
          "in",
          "    #\"Changed Type4\""
        ],
        "kind": "m",
        "lineageTag": "aae6028b-2f3c-4439-8395-aaa0c2146e8c",
        "queryGroup": "Schema"
      },
      {
        "name": "Product Index",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"SP Connection - Data\",",
          "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Costing Variant\", type text}, {\"Valuation area\", Int64.Type}, {\"FG Item Code\", Int64.Type}, {\"FG Item Code Description\", type text}, {\"Item Category\", type text}, {\"Cost Estimate Number\", Int64.Type}, {\"Item Code\", type text}, {\"Item Code Description\", type text}, {\"Costing Date\", Int64.Type}, {\"Cost Element\", Int64.Type}, {\"G/L Acct Long Text\", type text}, {\"TOTAL\", type number}, {\"QTY\", type number}, {\"UOM SAP\", type text}, {\"REPL Code\", Int64.Type}, {\"REPL Code Description\", type text}, {\"BOM Usage\", Int64.Type}, {\"Alternative BOM\", Int64.Type}, {\"Item (SD)\", Int64.Type}, {\"Main Plant\", Int64.Type}, {\"REPL Qty\", type number}, {\"REPL UOM\", type text}, {\"Vendor\", Int64.Type}, {\"Vendor Name\", type text}, {\"Comp Denom\", Int64.Type}, {\"Converted Base Qty\", type number}, {\"Base Unit of Measure\", type text}, {\"REPL Price\", type number}, {\"REPL Currency\", type text}, {\"PIR Price per UOM\", Int64.Type}, {\"Order Price Unit\", type text}, {\"PIR Denom\", Int64.Type}, {\"PIR Counter\", Int64.Type}, {\"PIR Base Net Price\", type number}, {\"Component Price\", type number}, {\"FX / FOREX\", type number}, {\"REPL FOB in PHP\", type number}, {\"ZFRF\", type number}, {\"ZDTX\", Int64.Type}, {\"ZOTH\", Int64.Type}, {\"ZBRO\", Int64.Type}, {\"ZINS\", Int64.Type}, {\"REPL LCF Rate\", Percentage.Type}, {\"REPL LCF Amount\", type number}, {\"REPL Total\", type number}, {\"Standard price\", type number}, {\"Standard Usage\", type number}, {\"Usage Variance\", type number}, {\"Material Group\", Int64.Type}, {\"Material Group Desc\", type text}}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type\",\"\",\"BLANK\",Replacer.ReplaceValue,{\"FG Item Code Description\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"Costing Date\", type date}}),",
          "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Changed Type1\",\"\",\"BLANK\",Replacer.ReplaceValue,{\"Vendor Name\"})",
          "in",
          "    #\"Replaced Value1\""
        ],
        "kind": "m",
        "lineageTag": "f1ed5160-5aff-427c-87ee-5cea5765b8d9",
        "queryGroup": "Schema"
      },
      {
        "name": "SP Connection - Material Mapping",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = SharePoint.Files(\"https://phccac.sharepoint.com/sites/MIS-UATBIandSolutioning/\", [ApiVersion = 15]),",
          "    #\"Material Code Mapping xlsx_https://phccac sharepoint com/sites/MIS-UATBIandSolutioning/Shared Documents/FACTORY FINANCE UAT/PRODUCT COST INDEX/\" = Source{[Name=\"Material Code Mapping.xlsx\",#\"Folder Path\"=\"https://phccac.sharepoint.com/sites/MIS-UATBIandSolutioning/Shared Documents/FACTORY FINANCE UAT/PRODUCT COST INDEX/\"]}[Content]",
          "in",
          "    #\"Material Code Mapping xlsx_https://phccac sharepoint com/sites/MIS-UATBIandSolutioning/Shared Documents/FACTORY FINANCE UAT/PRODUCT COST INDEX/\""
        ],
        "kind": "m",
        "lineageTag": "28cf8699-edcc-457e-af77-016c46df58da",
        "queryGroup": "Source Point"
      },
      {
        "name": "Material Mapping",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"SP Connection - Material Mapping\",",
          "    #\"Imported Excel Workbook\" = Excel.Workbook(Source),",
          "    Sheet1_Sheet = #\"Imported Excel Workbook\"{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product Category\", type text}, {\"Product Class\", type text}, {\"Classification\", type text}, {\"Capacity\", type number}, {\"Material\", Int64.Type}, {\"Material Description\", type text}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "76fec3d4-b163-4f7a-925a-e23c8a13784c",
        "queryGroup": "Schema"
      },
      {
        "name": "SP Connection - Inventory Reference",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = SharePoint.Files(\"https://phccac.sharepoint.com/sites/MIS-UATBIandSolutioning/\", [ApiVersion = 15]),",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Folder Path] = \"https://phccac.sharepoint.com/sites/MIS-UATBIandSolutioning/Shared Documents/FACTORY FINANCE UAT/PRODUCT COST INDEX/Inventory MB51 raw/\")),",
          "    #\"Filtered Hidden Files1\" = Table.SelectRows(#\"Filtered Rows\", each [Attributes]?[Hidden]? <> true),",
          "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File\", each #\"Transform File\"([Content])),",
          "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
          "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File\"}),",
          "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File\", Table.ColumnNames(#\"Transform File\"(#\"Sample File\"))),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"Material\", Int64.Type}, {\"Material description\", type text}, {\"Plant\", Int64.Type}, {\"Storage location\", type text}, {\"Cost Center\", type any}, {\"Batch\", Int64.Type}, {\"Movement type\", Int64.Type}, {\"Special Stock\", type any}, {\"Material Document\", Int64.Type}, {\"Entry Date\", type date}, {\"Time of Entry\", type datetime}, {\"Vendor\", type any}, {\"Order\", Int64.Type}, {\"Purchase order\", type any}, {\"Qty in unit of entry\", Int64.Type}, {\"Unit of Entry\", type text}, {\"User Name\", type text}, {\"Document Header Text\", Int64.Type}, {\"Reference\", Int64.Type}, {\"Amt.in Loc.Cur.\", type number}, {\"Name 1\", type text}, {\"Movement Type Text\", type text}, {\"Material Doc.Item\", Int64.Type}, {\"Posting Date\", type date}, {\"Asset\", type any}, {\"Sub-number\", type any}, {\"Counter\", Int64.Type}, {\"Routing number for operations\", Int64.Type}, {\"Document Date\", type date}, {\"Qty in OPUn\", Int64.Type}, {\"Order Price Unit\", type any}, {\"Order Unit\", type text}, {\"Qty in order unit\", Int64.Type}, {\"Company Code\", Int64.Type}, {\"Valuation Type\", type any}, {\"Smart Number\", type any}, {\"Item\", Int64.Type}, {\"Ext. Amount in Local Currency\", Int64.Type}, {\"Sales Value\", Int64.Type}, {\"Reason for Movement\", Int64.Type}, {\"Sales Order\", type any}, {\"Sales order schedule\", Int64.Type}, {\"Sales order item\", Int64.Type}, {\"Customer\", type any}, {\"Movement indicator\", type text}, {\"Consumption\", type any}, {\"Receipt Indicator\", type any}, {\"Sales order.1\", type any}, {\"Sales order item_1\", Int64.Type}, {\"Base Unit of Measure\", type text}, {\"Quantity\", Int64.Type}, {\"Material Doc. Year\", Int64.Type}, {\"Network\", type any}, {\"Activity\", type any}, {\"WBS element\", type any}, {\"Reservation\", Int64.Type}, {\"Item number of reservation\", Int64.Type}, {\"G/L Account\", Int64.Type}, {\"Debit/Credit ind\", type text}, {\"Trans./Event Type\", type text}, {\"Sales Value inc. VAT\", Int64.Type}, {\"Currency\", type text}, {\"Goods Receipt/Issue Slip\", type any}, {\"Item automatically created\", type any}, {\"Original Line Item\", Int64.Type}, {\"Multiple Account Assignment\", type any}}),",
          "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"Material\", \"Material description\", \"Movement type\", \"Entry Date\", \"Qty in unit of entry\"}),",
          "    #\"Extracted Month Name\" = Table.TransformColumns(#\"Removed Other Columns\", {{\"Entry Date\", each Date.MonthName(_), type text}}),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Extracted Month Name\",{\"Material\", \"Material description\", \"Movement type\", \"Qty in unit of entry\", \"Entry Date\"})",
          "in",
          "    #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "e03a3e87-20c1-4e7b-b502-07771c159a89",
        "queryGroup": "Source Point"
      },
      {
        "name": "Inventory Reference",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"SP Connection - Inventory Reference\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "cc9e7efe-954d-470b-96da-1f02e5c67c9c",
        "queryGroup": "Schema"
      },
      {
        "name": "SP Connection - 2023 Retail & Replacement Cost (Temporary)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = SharePoint.Files(\"https://phccac.sharepoint.com/sites/MIS-UATBIandSolutioning/\", [ApiVersion = 15]),",
          "    #\"2023_COST&REPLCOST xlsx_https://phccac sharepoint com/sites/MIS-UATBIandSolutioning/Shared Documents/FACTORY FINANCE UAT/PRODUCT COST INDEX/\" = Source{[Name=\"2023_COST&REPLCOST.xlsx\",#\"Folder Path\"=\"https://phccac.sharepoint.com/sites/MIS-UATBIandSolutioning/Shared Documents/FACTORY FINANCE UAT/PRODUCT COST INDEX/\"]}[Content]",
          "in",
          "    #\"2023_COST&REPLCOST xlsx_https://phccac sharepoint com/sites/MIS-UATBIandSolutioning/Shared Documents/FACTORY FINANCE UAT/PRODUCT COST INDEX/\""
        ],
        "kind": "m",
        "lineageTag": "14b46c92-9122-409f-ba71-c3b4ca4fb9d2",
        "queryGroup": "Source Point"
      },
      {
        "name": "2023 Retail & Replacement Cost (Temporary)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = #\"SP Connection - 2023 Retail & Replacement Cost (Temporary)\",",
          "    #\"Imported Excel Workbook\" = Excel.Workbook(Source),",
          "    Sheet1_Sheet = #\"Imported Excel Workbook\"{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Material Code\", Int64.Type}, {\"2023 #(lf)Standard Cost\", type number}, {\"2023 REPL @ ACT FX\", type number}})",
          "in",
          "    #\"Changed Type\""
        ],
        "kind": "m",
        "lineageTag": "994be8e0-26b1-462f-9d46-1d82c5fca573",
        "queryGroup": "Schema"
      },
      {
        "name": "SQL Connection - Master Material Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Sql.Database(\"10.10.2.49\", \"BIDev\", [Query=\"SELECT #(lf)[MaterialNumber]#(lf),[ProductHierarchyLevel2]#(lf),[ProductHierarchyLevel4]#(lf),[Division]#(lf),[MaterialDescription]#(lf),[MaterialGroup1] as [Brand]#(lf)  FROM [BIDev].[dbo].[MDM_MaterialMasterData_vw]#(lf)  WHERE [MaterialNumber] BETWEEN '1000000000' and '1999999999'\"])",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "dc2d283d-e2dd-440f-af39-77ea271f9502",
        "queryGroup": "Source Point"
      },
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "96d3e7ed-b8ed-41ff-8483-f3fcdf6fd138",
        "queryGroup": "Source Point\\Transform File from SP Connection - Inventory Reference\\Helper Queries"
      },
      {
        "name": "Transform Sample File",
        "expression": [
          "let",
          "    Source = Excel.Workbook(Parameter1, null, true),",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Promoted Headers\",{{\"Sales order\", \"Sales order.1\"}})",
          "in",
          "    #\"Renamed Columns\""
        ],
        "kind": "m",
        "lineageTag": "165e0197-7f8d-4e98-adf2-f3289dabf1bc",
        "queryGroup": "Source Point\\Transform File from SP Connection - Inventory Reference"
      },
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = SharePoint.Files(\"https://phccac.sharepoint.com/sites/MIS-UATBIandSolutioning/\", [ApiVersion = 15]),",
          "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Folder Path] = \"https://phccac.sharepoint.com/sites/MIS-UATBIandSolutioning/Shared Documents/FACTORY FINANCE UAT/PRODUCT COST INDEX/Inventory MB51 raw/\")),",
          "    Navigation1 = #\"Filtered Rows\"{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "72ec6616-c80e-4739-afdc-1967cc46c125",
        "queryGroup": "Source Point\\Transform File from SP Connection - Inventory Reference\\Helper Queries"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "    Source = Excel.Workbook(Parameter1, null, true),",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Promoted Headers\",{{\"Sales order\", \"Sales order.1\"}})",
          "in",
          "    #\"Renamed Columns\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "7fb4d000-de1e-4803-92aa-87d53533616c",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "queryGroup": "Source Point\\Transform File from SP Connection - Inventory Reference\\Helper Queries"
      },
      {
        "name": "Parameter2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (2)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (2)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "627b64d1-3bdd-42ca-8a6d-41cbea3dbe78",
        "queryGroup": "Source Point\\Transform File from SP Connection - Data\\Helper Queries"
      },
      {
        "name": "Transform Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(Parameter2, null, true),",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "f164899d-4b6b-4bc7-ab61-8dbfa74a4eb2",
        "queryGroup": "Source Point\\Transform File from SP Connection - Data"
      },
      {
        "name": "Sample File (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = SharePoint.Files(\"https://phccac.sharepoint.com/sites/MIS-UATBIandSolutioning/\", [ApiVersion = 15]),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(Source,{\"Folder Path\", \"Content\", \"Name\", \"Extension\", \"Date accessed\", \"Date modified\", \"Date created\", \"Attributes\"}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Reordered Columns\", each ([Folder Path] = \"https://phccac.sharepoint.com/sites/MIS-UATBIandSolutioning/Shared Documents/FACTORY FINANCE UAT/PRODUCT COST INDEX/ZCOR001 Raw/\")),",
          "    Navigation1 = #\"Filtered Rows\"{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "155c5832-29bf-45e0-9907-c3ea3b4e7dc8",
        "queryGroup": "Source Point\\Transform File from SP Connection - Data\\Helper Queries"
      },
      {
        "name": "Transform File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter2 as binary) => let",
          "    Source = Excel.Workbook(Parameter2, null, true),",
          "    Sheet1_Sheet = Source{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "41dc8a0a-d73b-4c12-babf-0a19752f0cab",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File (2)\"\"}\" ]",
        "queryGroup": "Source Point\\Transform File from SP Connection - Data\\Helper Queries"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Schema"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Source Point"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Data Configs"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "Data Tables"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Source Point\\Transform File from SP Connection - Inventory Reference"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Source Point\\Transform File from SP Connection - Inventory Reference\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Source Point\\Transform File from SP Connection - Data"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Source Point\\Transform File from SP Connection - Data\\Helper Queries"
      }
    ],
    "relationships": [
      {
        "name": "68f3c94d-5f33-4ef8-9232-e5a66f51cdaf",
        "fromColumn": "Costing Date",
        "fromTable": "Product Cost Index Transformed",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_12aeca20-1dfb-4745-9e98-fa940aae8f6b"
      },
      {
        "name": "AutoDetected_d5b3b19a-33a0-478e-91d2-4cc86bb4e012",
        "fromColumn": "Month",
        "fromTable": "Product Cost Index Transformed",
        "toColumn": "Month",
        "toTable": "Rolling Calendar Config"
      },
      {
        "name": "b5de4d4f-cd58-d6b2-d99d-1a5a94bc6431",
        "fromColumn": "FG Item Code",
        "fromTable": "Product Cost Index Transformed",
        "toColumn": "Material",
        "toTable": "Material Code Config"
      },
      {
        "name": "c597321b-896c-4385-88ff-b9afdd4b6e7d",
        "fromColumn": "Date",
        "fromTable": "Rolling Calendar Config",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_07179c71-eae1-4574-9a32-16e5867a11f0"
      },
      {
        "name": "AutoDetected_19dca4ab-b111-4b16-8b13-1136c05acc93",
        "fromColumn": "Material",
        "fromTable": "Inventory Production Config",
        "toColumn": "Material",
        "toTable": "Material Code Config"
      },
      {
        "name": "a928f272-5c75-8699-918e-ebd4a260885f",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Material",
        "fromTable": "Inventory Production Config",
        "toCardinality": "many",
        "toColumn": "FG Item Code",
        "toTable": "Product Cost Index Transformed"
      },
      {
        "name": "37aa0a37-7a13-fe2e-2b5a-e670e5908354",
        "fromColumn": "FG Item Code",
        "fromTable": "Product Cost Index Transformed",
        "toColumn": "Material Code",
        "toTable": "DimReplacement Cost"
      }
    ],
    "sourceQueryCulture": "en-PH",
    "tables": [
      {
        "name": "DateTableTemplate_27b1a5b7-a854-4ae4-846a-5272845fac8e",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "41e9fa31-bb85-46f3-95ac-c085bfd6c59d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c36fe838-a16b-4cc0-acb8-20e22d5d6f8c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "71b4a08a-d1ab-4e72-b15f-30034cb58396",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "df165432-8f2b-40fa-a54c-9f0e9cf0075f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f6297763-a08c-422b-8581-2c46024c55df",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5868d736-b7a8-4d52-ab99-787bdc43cdd1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "763f79b0-d8bf-4d0d-b135-3173c2b27c77",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9a37ca2c-cb67-44bd-a876-aad1fe5112d9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a5daa846-b1af-4757-a6ca-77d68d37d6e7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0de00a7e-9a37-4ad3-8482-0b2136241266",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "842eb563-5165-47e8-8c7a-6c59a72c4528",
                "ordinal": 3
              }
            ],
            "lineageTag": "39274581-42aa-43b7-8cd6-7d16027f08d9"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "e7c24911-8120-4a37-b634-c332db605525",
        "partitions": [
          {
            "name": "DateTableTemplate_27b1a5b7-a854-4ae4-846a-5272845fac8e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Rolling Calendar Config",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ISO WEEK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "74045cd3-8ea3-494c-b632-baee48ffdeaf",
            "sourceColumn": "ISO WEEK",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f126b2d9-1c68-47c2-a087-9092db16055b",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d5056d3e-4da3-45f5-be75-d1c5e8a372f8",
            "sourceColumn": "Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "17210d18-5de8-457a-a693-cd6a6aa25843",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month-Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "067d2eb0-5944-4de5-bff8-c985f145671f",
            "sourceColumn": "Month-Year",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9a786951-28f6-4efe-9ccc-1835e4136309",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_07179c71-eae1-4574-9a32-16e5867a11f0"
                },
                "isDefault": true,
                "relationship": "c597321b-896c-4385-88ff-b9afdd4b6e7d"
              }
            ]
          },
          {
            "name": "Quarter Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f5e54b7-2cc5-4b5f-880f-b29e3368a381",
            "sourceColumn": "Quarter Year",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4a01545e-0e82-4707-b88d-06c1508e97ee",
        "partitions": [
          {
            "name": "Rolling Calendar Config",
            "mode": "import",
            "queryGroup": "Data Configs",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Dynamic Calendar\",",
                "    #\"Removed Columns\" = Table.RemoveColumns(Source,{\"CurrentThursday\", \"YearCurrentThursday\", \"FirstThursdayOfYear\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\", {\"Month\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product Cost Index Transformed",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Costing Variant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96ea98f0-5b50-4e7a-8f28-36b0fdd9b6be",
            "sourceColumn": "Costing Variant",
            "summarizeBy": "none"
          },
          {
            "name": "Valuation area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "60ca69cb-cbc9-4906-8db9-334128a93cc1",
            "sourceColumn": "Valuation area",
            "summarizeBy": "sum"
          },
          {
            "name": "FG Item Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5e824c12-4f81-41f0-b508-064e4ed4980c",
            "sourceColumn": "FG Item Code",
            "summarizeBy": "none"
          },
          {
            "name": "FG Item Code Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a91b328-cdcc-46e9-a8b8-d8175d98c413",
            "sourceColumn": "FG Item Code Description",
            "summarizeBy": "none"
          },
          {
            "name": "Item Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ecfebaf-927f-4ce2-9393-45194c236aca",
            "sourceColumn": "Item Category",
            "summarizeBy": "none"
          },
          {
            "name": "Cost Estimate Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b2507806-b8b9-43c6-a6af-33296dd9b024",
            "sourceColumn": "Cost Estimate Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Item Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7f76c04-b08a-41ec-9fb2-fb7d90c579e7",
            "sourceColumn": "Item Code",
            "summarizeBy": "none"
          },
          {
            "name": "Item Code Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8bed5a5-e6d1-4648-b776-bc4c4844ca14",
            "sourceColumn": "Item Code Description",
            "summarizeBy": "none"
          },
          {
            "name": "Costing Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8286a82e-3040-4cb8-ab7b-f74cb2fb79f8",
            "sourceColumn": "Costing Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_12aeca20-1dfb-4745-9e98-fa940aae8f6b"
                },
                "isDefault": true,
                "relationship": "68f3c94d-5f33-4ef8-9232-e5a66f51cdaf"
              }
            ]
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "98d5f7d9-a27d-487d-8003-f49aebf6a894",
            "sourceColumn": "Week",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63be605a-ce80-4f23-be11-fe83ee32f4a9",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b733c362-910c-45d0-bc36-6d3be785c4e9",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97e6eba6-002f-480c-95de-39fd33870e8c",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Cost Element",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "289d88fe-d4bd-470d-bd25-86f34cac9e16",
            "sourceColumn": "Cost Element",
            "summarizeBy": "sum"
          },
          {
            "name": "G/L Acct Long Text",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebac6972-d341-4082-af55-070a55bf1de0",
            "sourceColumn": "G/L Acct Long Text",
            "summarizeBy": "none"
          },
          {
            "name": "TOTAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0fca0bc1-7db9-4425-9868-7eb103ea70a8",
            "sourceColumn": "TOTAL",
            "summarizeBy": "sum"
          },
          {
            "name": "QTY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c28895d1-14b6-44f8-8520-29a881fe8344",
            "sourceColumn": "QTY",
            "summarizeBy": "sum"
          },
          {
            "name": "UOM SAP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "270e0c17-24a5-432c-9485-bac1c2c8d3fa",
            "sourceColumn": "UOM SAP",
            "summarizeBy": "none"
          },
          {
            "name": "REPL Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b95b011d-b71f-4881-a37f-46ce6c812684",
            "sourceColumn": "REPL Code",
            "summarizeBy": "count"
          },
          {
            "name": "REPL Code Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dec2bcf1-c174-4007-acfa-2d4e29379383",
            "sourceColumn": "REPL Code Description",
            "summarizeBy": "none"
          },
          {
            "name": "BOM Usage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "47457dce-c100-4f94-87b4-f879974cc4b2",
            "sourceColumn": "BOM Usage",
            "summarizeBy": "sum"
          },
          {
            "name": "Alternative BOM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "71faf96d-9ea9-4630-a2af-ede048e91fee",
            "sourceColumn": "Alternative BOM",
            "summarizeBy": "sum"
          },
          {
            "name": "Item (SD)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "83dcf24e-e45c-4862-ae40-be89198f4051",
            "sourceColumn": "Item (SD)",
            "summarizeBy": "sum"
          },
          {
            "name": "Main Plant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b09d8954-166e-4bc3-b8b7-5113b3d0e42a",
            "sourceColumn": "Main Plant",
            "summarizeBy": "sum"
          },
          {
            "name": "REPL Qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a8b70644-6b6c-47db-b823-089587985efe",
            "sourceColumn": "REPL Qty",
            "summarizeBy": "sum"
          },
          {
            "name": "REPL UOM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07d07a1e-2124-4173-9409-9232bccf79ad",
            "sourceColumn": "REPL UOM",
            "summarizeBy": "none"
          },
          {
            "name": "Vendor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59ac6447-83cb-47c5-a7cb-48ec3f58059c",
            "sourceColumn": "Vendor",
            "summarizeBy": "sum"
          },
          {
            "name": "Vendor Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95eb46c2-ef39-431d-9dad-b9ae7fbbc1bc",
            "sourceColumn": "Vendor Name",
            "summarizeBy": "none"
          },
          {
            "name": "Comp Denom",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "096ffdeb-6c4a-48fc-808c-c27e22efc8b4",
            "sourceColumn": "Comp Denom",
            "summarizeBy": "sum"
          },
          {
            "name": "Converted Base Qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "441489ac-4764-4d78-9575-11ccd2347c19",
            "sourceColumn": "Converted Base Qty",
            "summarizeBy": "sum"
          },
          {
            "name": "Base Unit of Measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8291dfc4-d747-4326-9923-1092354a0dd8",
            "sourceColumn": "Base Unit of Measure",
            "summarizeBy": "none"
          },
          {
            "name": "REPL Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f41b246d-0772-47cc-b3de-2a0a4d26e5e0",
            "sourceColumn": "REPL Price",
            "summarizeBy": "sum"
          },
          {
            "name": "REPL Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "811cd769-c93d-4157-b0bc-87816872ae2f",
            "sourceColumn": "REPL Currency",
            "summarizeBy": "none"
          },
          {
            "name": "PIR Price per UOM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "36927e57-1325-488b-8d8b-55d118a92971",
            "sourceColumn": "PIR Price per UOM",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Price Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa211659-35b4-44d8-80a5-ac43e552bdfc",
            "sourceColumn": "Order Price Unit",
            "summarizeBy": "none"
          },
          {
            "name": "PIR Denom",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "729ed98d-2ace-4a15-9142-300362e8866a",
            "sourceColumn": "PIR Denom",
            "summarizeBy": "sum"
          },
          {
            "name": "PIR Counter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7c934cdf-40c9-4d36-92ef-d58a10b06b43",
            "sourceColumn": "PIR Counter",
            "summarizeBy": "sum"
          },
          {
            "name": "PIR Base Net Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4259028c-5cbb-4df7-9ecd-95d09a34bb82",
            "sourceColumn": "PIR Base Net Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Component Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "39b8d431-849c-4859-b31d-e02d0777785f",
            "sourceColumn": "Component Price",
            "summarizeBy": "sum"
          },
          {
            "name": "FX / FOREX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "41e8900a-b451-4ec5-b3f3-eb6af9712ef4",
            "sourceColumn": "FX / FOREX",
            "summarizeBy": "sum"
          },
          {
            "name": "REPL FOB in PHP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8b66fa93-ce97-4da4-bd83-9f26d017b07f",
            "sourceColumn": "REPL FOB in PHP",
            "summarizeBy": "sum"
          },
          {
            "name": "ZFRF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7acddd20-b975-41af-8a8d-bc8df8106155",
            "sourceColumn": "ZFRF",
            "summarizeBy": "sum"
          },
          {
            "name": "ZDTX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "182c1113-3843-4f0e-a177-28e0acaeeb89",
            "sourceColumn": "ZDTX",
            "summarizeBy": "sum"
          },
          {
            "name": "ZOTH",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "154e7edd-d04c-4067-bd92-48166157b8be",
            "sourceColumn": "ZOTH",
            "summarizeBy": "sum"
          },
          {
            "name": "ZBRO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8bf648f0-622b-4afd-b9db-d585931a47c2",
            "sourceColumn": "ZBRO",
            "summarizeBy": "sum"
          },
          {
            "name": "ZINS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "465b0980-f7d6-40e0-8584-2561e9eceb78",
            "sourceColumn": "ZINS",
            "summarizeBy": "sum"
          },
          {
            "name": "REPL LCF Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0c3b210e-4c2f-4aa0-ba7f-800601a02952",
            "sourceColumn": "REPL LCF Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "REPL LCF Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ec7cdada-daf6-4c5f-924d-875597e4aff0",
            "sourceColumn": "REPL LCF Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "REPL Total",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fa8890af-69d1-4329-af4b-11ad86afce4e",
            "sourceColumn": "REPL Total",
            "summarizeBy": "sum"
          },
          {
            "name": "Standard price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7ba28166-9ee1-42b2-ad60-54162a4b7e13",
            "sourceColumn": "Standard price",
            "summarizeBy": "sum"
          },
          {
            "name": "Standard Usage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "829a61f7-8a85-4b3f-8498-5d87d7164546",
            "sourceColumn": "Standard Usage",
            "summarizeBy": "sum"
          },
          {
            "name": "Usage Variance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a28c1728-1ab2-493a-aa22-9d4dab1a64e7",
            "sourceColumn": "Usage Variance",
            "summarizeBy": "sum"
          },
          {
            "name": "Material Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9710afb-3934-4328-bbc6-d81374dea115",
            "sourceColumn": "Material Group",
            "summarizeBy": "sum"
          },
          {
            "name": "Material Group Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6073fe12-c874-4ea3-a55d-7d4a44df99bb",
            "sourceColumn": "Material Group Desc",
            "summarizeBy": "none"
          },
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "763e0613-e855-4d4b-93be-0de2b7886b23",
            "sourceColumn": "Product Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47debb67-3b3c-43dc-9e2a-e06c7194d092",
            "sourceColumn": "Product Class",
            "summarizeBy": "none"
          },
          {
            "name": "Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5f04002e-f554-492b-9bd4-41ab0a9ab3bd",
            "sourceColumn": "Capacity",
            "summarizeBy": "sum"
          },
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a0c3b1c-c9f6-4cab-9f87-8ac71f86c49c",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8789cfc8-4751-470f-afc6-045946a8538d",
        "partitions": [
          {
            "name": "Product Cost Index Transformed",
            "mode": "import",
            "queryGroup": "Data Tables",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Product Index\",",
                "    #\"Merged Calendar\" = Table.NestedJoin(Source, {\"Costing Date\"}, #\"Dynamic Calendar\", {\"Date\"}, \"DynamicCalendar\", JoinKind.LeftOuter),",
                "    #\"Expanded DynamicCalendar\" = Table.ExpandTableColumn(#\"Merged Calendar\", \"DynamicCalendar\", {\"ISO WEEK\", \"Month\", \"Year\", \"Quarter Year\"}, {\"DynamicCalendar.ISO WEEK\", \"DynamicCalendar.Month\", \"DynamicCalendar.Year\", \"DynamicCalendar.Quarter Year\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Expanded DynamicCalendar\",{{\"DynamicCalendar.ISO WEEK\", \"Week\"}, {\"DynamicCalendar.Month\", \"Month\"}, {\"DynamicCalendar.Year\", \"Year\"}, {\"DynamicCalendar.Quarter Year\", \"Quarter\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns\",{\"Costing Variant\", \"Valuation area\", \"FG Item Code\", \"FG Item Code Description\", \"Item Category\", \"Cost Estimate Number\", \"Item Code\", \"Item Code Description\", \"Costing Date\", \"Week\", \"Month\", \"Year\", \"Quarter\", \"Cost Element\", \"G/L Acct Long Text\", \"TOTAL\", \"QTY\", \"UOM SAP\", \"REPL Code\", \"REPL Code Description\", \"BOM Usage\", \"Alternative BOM\", \"Item (SD)\", \"Main Plant\", \"REPL Qty\", \"REPL UOM\", \"Vendor\", \"Vendor Name\", \"Comp Denom\", \"Converted Base Qty\", \"Base Unit of Measure\", \"REPL Price\", \"REPL Currency\", \"PIR Price per UOM\", \"Order Price Unit\", \"PIR Denom\", \"PIR Counter\", \"PIR Base Net Price\", \"Component Price\", \"FX / FOREX\", \"REPL FOB in PHP\", \"ZFRF\", \"ZDTX\", \"ZOTH\", \"ZBRO\", \"ZINS\", \"REPL LCF Rate\", \"REPL LCF Amount\", \"REPL Total\", \"Standard price\", \"Standard Usage\", \"Usage Variance\", \"Material Group\", \"Material Group Desc\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Reordered Columns\", each true),",
                "    #\"Merged Material\" = Table.NestedJoin(#\"Filtered Rows\", {\"FG Item Code\"}, #\"Material Code Config\", {\"Material\"}, \"Material Code Config\", JoinKind.LeftOuter),",
                "    #\"Expanded Material Code Config\" = Table.ExpandTableColumn(#\"Merged Material\", \"Material Code Config\", {\"Product Category\", \"Product Class\", \"Classification\", \"Capacity\"}, {\"Product Category\", \"Product Class\", \"Classification\", \"Capacity\"}),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Expanded Material Code Config\",{\"Costing Variant\", \"Valuation area\", \"Product Category\", \"Product Class\", \"Capacity\", \"Classification\", \"FG Item Code\", \"FG Item Code Description\", \"Item Category\", \"Cost Estimate Number\", \"Item Code\", \"Item Code Description\", \"Costing Date\", \"Week\", \"Month\", \"Year\", \"Quarter\", \"Cost Element\", \"G/L Acct Long Text\", \"TOTAL\", \"QTY\", \"UOM SAP\", \"REPL Code\", \"REPL Code Description\", \"BOM Usage\", \"Alternative BOM\", \"Item (SD)\", \"Main Plant\", \"REPL Qty\", \"REPL UOM\", \"Vendor\", \"Vendor Name\", \"Comp Denom\", \"Converted Base Qty\", \"Base Unit of Measure\", \"REPL Price\", \"REPL Currency\", \"PIR Price per UOM\", \"Order Price Unit\", \"PIR Denom\", \"PIR Counter\", \"PIR Base Net Price\", \"Component Price\", \"FX / FOREX\", \"REPL FOB in PHP\", \"ZFRF\", \"ZDTX\", \"ZOTH\", \"ZBRO\", \"ZINS\", \"REPL LCF Rate\", \"REPL LCF Amount\", \"REPL Total\", \"Standard price\", \"Standard Usage\", \"Usage Variance\", \"Material Group\", \"Material Group Desc\"})",
                "in",
                "    #\"Reordered Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_12aeca20-1dfb-4745-9e98-fa940aae8f6b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "32661b19-e5c1-450d-b840-1ad8f25f6ed2",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e1066937-dc2a-4af2-8560-99a55c5b52c8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ab8955e5-d3ab-4749-b816-8935c7a2beba",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a62bf204-510b-46b4-8118-d28de6f9f227",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "548fc76c-9577-4cd7-b74b-1894d59801ba",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f78781f0-6684-4e4c-86ee-a23b863a2098",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6b5f13e8-8320-4e5a-9612-f0a1bc515567",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e3a783c8-3c99-4141-97c3-9c9082cbcdea",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f2a073a2-635c-4d7f-b76f-bdb7d174fc6f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0cc4052b-38ff-4680-8448-1e2e42c2fc2d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a21a1dba-822c-4171-9f6b-3a6e7c886403",
                "ordinal": 3
              }
            ],
            "lineageTag": "d16c306a-10e7-4150-aef8-167e57476f26"
          }
        ],
        "isHidden": true,
        "lineageTag": "189670ac-3845-435a-84e1-62045ec943c1",
        "partitions": [
          {
            "name": "LocalDateTable_12aeca20-1dfb-4745-9e98-fa940aae8f6b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Product Cost Index Transformed'[Costing Date])), 1, 1), Date(Year(MAX('Product Cost Index Transformed'[Costing Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Calculation group",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Calculation item",
              "expression": "SELECTEDMEASURE()"
            }
          ]
        },
        "columns": [
          {
            "name": "0-0",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3db352c4-29a5-47b8-ae73-79780c5c8147",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27524514-7a41-4a05-b1c4-cc8f850e472f",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e54f73f6-1685-40e1-a8df-f81d5629a8aa",
        "measures": [
          {
            "name": "CSH",
            "expression": "CALCULATE(SUM('Product Cost Index Transformed'[QTY]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Burden OH\")",
            "formatString": "#,0.000",
            "lineageTag": "ddae21d3-6961-4609-a9de-33b333c5fb5f"
          },
          {
            "name": "Cost Material",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Consumption - Raw Materials\") + CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Consumption - Finished Goods\") + CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Additives / Spoilage\") + CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Indirect Materials\")",
            "formatString": "#,0",
            "lineageTag": "ba66a650-bf0f-463b-a670-cbf667b58eaa"
          },
          {
            "name": "Cost Labor",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Direct Labor\") + CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Fixed Cost\") + CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Variable Cost\") + CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Labor Surcharge 1\") + CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Labor Surcharge 2\")",
            "formatString": "#,0",
            "lineageTag": "0de2ae40-fd60-4190-af60-b0b524e2b0b0"
          },
          {
            "name": "2024 Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "[Cost Labor]+[Cost Material]+[Cost Overhead]",
            "formatString": "#,0",
            "lineageTag": "b7456aaf-26fb-4362-ae18-8ef042e48d1f"
          },
          {
            "name": "Cost Overhead",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Burden OH\")",
            "formatString": "#,0",
            "lineageTag": "f0475cac-d58c-47d8-be66-2f46062bbc91"
          },
          {
            "name": "Replacement Cost Material",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(SUM('Product Cost Index Transformed'[REPL Total]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Consumption - Raw Materials\") + ",
              "CALCULATE(SUM('Product Cost Index Transformed'[REPL Total]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Consumption - Finished Goods\") + ",
              "CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Additives / Spoilage\") + ",
              "CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Indirect Materials\")"
            ],
            "formatString": "#,0",
            "lineageTag": "8c87842e-1be3-4c2a-9d6f-95241ce90377"
          },
          {
            "name": "Replacement Cost Labor",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Direct Labor\") + CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Fixed Cost\") + CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Variable Cost\") + CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Labor Surcharge 1\") + CALCULATE(SUM('Product Cost Index Transformed'[TOTAL]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Labor Surcharge 2\")",
            "formatString": "#,0",
            "lineageTag": "9a59afca-fdc0-4fb9-aa4a-347a2ab3b371"
          },
          {
            "name": "Replacement Cost Overhead",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "[CSH]*395.82",
            "formatString": "#,0",
            "lineageTag": "34fc51ef-4683-4ce7-ab01-b951041d8273"
          },
          {
            "name": "Difference Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "[2024 Cost]-[2024 Replacement Cost]",
            "formatString": "#,0",
            "lineageTag": "7da4f926-d4f6-4b7d-b533-189fc9b6949b"
          },
          {
            "name": "2024 Replacement Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "[Replacement Cost Labor] +",
              "[Replacement Cost Material] +",
              "[Replacement Cost Overhead]"
            ],
            "formatString": "#,0",
            "lineageTag": "8854f51d-2031-4a29-b295-bf2373f09e2a"
          },
          {
            "name": "Difference Material",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "[Cost Material] - [Replacement Cost Material]",
            "formatString": "#,0",
            "lineageTag": "b6bb589a-b394-475b-8654-9a7785ef2382"
          },
          {
            "name": "Difference Labor",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "[Cost Labor] - [Replacement Cost Labor]",
            "formatString": "#,0",
            "lineageTag": "d56a506e-fb3e-466a-b8e1-f99f237800bf"
          },
          {
            "name": "Difference Overhead",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "[Cost Overhead] - [Replacement Cost Overhead]",
            "formatString": "#,0",
            "lineageTag": "93373caa-452a-45b2-979e-8c1f1d867226"
          },
          {
            "name": "Cost %",
            "expression": "DIVIDE([Difference Cost],[2024 Cost])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "e781a609-31ba-4e24-a559-8dca2decec93"
          },
          {
            "name": "Material %",
            "expression": "DIVIDE([Difference Material],[Cost Material]) ",
            "formatString": "0%;-0%;0%",
            "lineageTag": "f24df146-dfe2-4fdb-b5d8-c912c1a7d384"
          },
          {
            "name": "Labor %",
            "expression": "DIVIDE([Difference Labor],[Cost Labor])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "44e5b747-2b3b-4170-81b3-5dc42d808e0e"
          },
          {
            "name": "Overhead %",
            "expression": "DIVIDE([Difference Overhead],[Cost Overhead]) ",
            "formatString": "0%;-0%;0%",
            "lineageTag": "f5b5baaa-ea56-4ad2-bd4a-9fca3f5a68b7"
          },
          {
            "name": "YTD Production Output",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Entry Date] = MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "25b6dc54-cb73-40c3-924e-4149a7f09b4e"
          },
          {
            "name": "Overall AE",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Product Class]=\"AE\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "6824c50a-c92c-46c8-9168-e8d024729bc8"
          },
          {
            "name": "Overall PE",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Product Class]=\"PE\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "7da56e31-c630-455b-885f-f89305e7c369"
          },
          {
            "name": "Overall WRAC",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Product Class]=\"WRAC\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "cad521ec-ffd8-419c-8aa8-f43a224fc2c0"
          },
          {
            "name": "WRAC-Fixed Speed Total",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Classification]=\"WRAC-Fixed Speed\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "dc31fafd-6db2-46de-9d35-cce3e6a828a4"
          },
          {
            "name": "WRAC-Variable Speed Total",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Classification]=\"WRAC-Variable Speed\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "8e729b14-b6bf-498e-8fa5-bdbe5bccac08"
          },
          {
            "name": "AEPE - Fixed Speed",
            "expression": "([AEPE-QTY AHU]+[AEPE-QTY FCU-CHW]+[AEPE-QTY HW CONV/SKD]+[AEPE-QTY Others]+[AEPE-QTY PCKGD APPLD]+[AEPE-QTY PCKGD CMMRCL]+[AEPE-QTY SLMPCK]+[AEPE-QTY STLTH]+[AEPE-QTY UNVRSL CDU])",
            "formatString": "0",
            "lineageTag": "af37260b-31b1-4f19-b43b-e2b6122cfa9f"
          },
          {
            "name": "AEPE - Variable Speed",
            "expression": "([AEPE-QTY SLMPCK-INV]+[AEPE-QTY OTHRS-INV])",
            "formatString": "0",
            "lineageTag": "138b65ee-e681-46c2-abd6-eef3acd2cb16"
          },
          {
            "name": "AEPE-QTY AHU",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model] = \"AIR HANDLING UNITS\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "88168b63-3ea3-4a4c-b765-403b4bc593a3"
          },
          {
            "name": "AEPE-QTY FCU-CHW",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model] = \"FCU-CHW\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "2cf0959a-5d80-4434-9291-8549c5ff418d"
          },
          {
            "name": "AEPE-QTY HW CONV/SKD",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model] = \"HW CONVERSION/SKD\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "f3ff7f8a-d197-4afc-8527-f1841e99b697"
          },
          {
            "name": "AEPE-QTY Others",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model] = \"Others\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "176b9542-8216-4fca-892c-b1e1c6641649"
          },
          {
            "name": "AEPE-QTY PCKGD APPLD",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model] = \"PACKAGED APPLIED\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "c9676e7c-9c28-44e7-b77f-e3ac708de008"
          },
          {
            "name": "AEPE-QTY PCKGD CMMRCL",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model] = \"PACKAGED COMMERCIAL\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "b0745b2b-8f0a-4483-a4b2-73b432c9255a"
          },
          {
            "name": "AEPE-QTY SLMPCK",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model] = \"SLIMPACK\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "fe11cd4a-102c-482e-9c80-9433140897a9"
          },
          {
            "name": "AEPE-QTY STLTH",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model] = \"STEALTH\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "4c4c23d6-9401-414d-ad79-e49eff4d86d6"
          },
          {
            "name": "AEPE-QTY UNVRSL CDU",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model] = \"UNIVERSAL CDU\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "936096c2-fbc5-4c05-aa2b-de53e29cd19f"
          },
          {
            "name": "AEPE-QTY SLMPCK-INV",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model] = \"SLIMPACK-INV\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "d1ed4b87-a9ad-4d5e-9242-cc9b33c2f69c"
          },
          {
            "name": "AEPE-QTY OTHRS-INV",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model] = \"OTHERS-INV\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "e1b681da-3593-4083-b684-d7d52e05e3f0"
          },
          {
            "name": "WRAC-QTY CHX",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model]=\"CHX\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "408ede9c-f2db-4e62-a721-20ddc1cdb1ce"
          },
          {
            "name": "WRAC-QTY CHG",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model]=\"CHG\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "2ba1de44-95fc-4317-98ab-ae6763a13440"
          },
          {
            "name": "WRAC-QTY CH2",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model]=\"CH2\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "507045fc-401c-4d11-9142-c63abe4512b1"
          },
          {
            "name": "WRAC-QTY CH3",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model]=\"CH3\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "a9b937ce-8d6d-48d0-a4ad-e84247a9a183"
          },
          {
            "name": "WRAC-QTY PMX",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model]=\"PMX\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "c430c1fb-693a-4654-b06c-66814db43372"
          },
          {
            "name": "WRAC-QTY CH2-INV",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model]=\"CH2-INV\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "aaa5cf93-7e07-490e-a10e-f423322bc8b4"
          },
          {
            "name": "WRAC-QTY CH3-INV",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model]=\"CH3-INV\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "7de6d95e-ebec-43cf-814a-b7841bd352c7"
          },
          {
            "name": "WRAC-QTY PMX-INV",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model]=\"PMX-INV\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "63f8a290-a3fa-495a-9656-1e1107712a0a"
          },
          {
            "name": "WRAC-QTY QSX-INV",
            "expression": [
              "",
              "VAR MonthSelected = SELECTEDVALUE('Rolling Calendar Config'[Month])",
              "RETURN",
              "CALCULATE(SUM('Inventory Production Config'[Qty in unit of entry]),'Inventory Production Config'[Model]=\"QSX-INV\",'Inventory Production Config'[Entry Date]=MonthSelected)"
            ],
            "formatString": "0",
            "lineageTag": "c84816c9-6fe7-4bc2-ac6e-b64f18ab85f7"
          },
          {
            "name": "QTY Labor",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('Product Cost Index Transformed'[QTY]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Direct Labor\") + CALCULATE(SUM('Product Cost Index Transformed'[QTY]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Fixed Cost\") + CALCULATE(SUM('Product Cost Index Transformed'[QTY]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Variable Cost\") + CALCULATE(SUM('Product Cost Index Transformed'[QTY]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Labor Surcharge 1\") + CALCULATE(SUM('Product Cost Index Transformed'[QTY]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Labor Surcharge 2\")",
            "lineageTag": "5ebe3e69-3f89-486d-ab43-66abff841c69"
          },
          {
            "name": "QTY Material",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('Product Cost Index Transformed'[QTY]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Consumption - Raw Materials\") + CALCULATE(SUM('Product Cost Index Transformed'[QTY]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Consumption - Finished Goods\") + CALCULATE(SUM('Product Cost Index Transformed'[QTY]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Additives / Spoilage\") + CALCULATE(SUM('Product Cost Index Transformed'[QTY]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Indirect Materials\")",
            "lineageTag": "2930f6bd-62ed-4290-a19f-fa1b002b4665"
          },
          {
            "name": "QTY Overhead",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('Product Cost Index Transformed'[QTY]),'Product Cost Index Transformed'[G/L Acct Long Text]=\"Burden OH\")",
            "lineageTag": "0998d670-a0bd-4fe6-929b-c2cda14e4497"
          },
          {
            "name": "2023 Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE('DimReplacement Cost'[2023 Standard Cost])",
            "lineageTag": "0ddf62ec-deb7-4090-b619-351b565fb3e7"
          },
          {
            "name": "2023 Replacement Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE('DimReplacement Cost'[2023 REPL @ ACT FX])",
            "lineageTag": "f2a1185c-7901-4c35-b343-48bfb77aa062"
          },
          {
            "name": "2023REPLvs2024REPL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Cost2023Replacement = AVERAGE('DimReplacement Cost'[2023 REPL @ ACT FX])",
              "VAR Cost2024Replacement = [Replacement Cost Labor] +[Replacement Cost Material]+[Replacement Cost Overhead]",
              "",
              "RETURN",
              "Cost2023Replacement-Cost2024Replacement"
            ],
            "lineageTag": "454e7bd6-15c9-4f55-8a99-7ac6372320d3"
          },
          {
            "name": "2023REPLvs2024REPL%",
            "expression": [
              "",
              "",
              "VAR Cost2023Replacement = AVERAGE('DimReplacement Cost'[2023 REPL @ ACT FX])",
              "VAR Cost2024Replacement = [Replacement Cost Labor] +[Replacement Cost Material]+[Replacement Cost Overhead]",
              "VAR Val2023REPLvs2024REPL = Cost2023Replacement-Cost2024Replacement",
              "",
              "RETURN ",
              "Val2023REPLvs2024REPL/Cost2023Replacement"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "de76ea98-13bb-4064-9862-1965a753b891"
          },
          {
            "name": "2024Costvs2024Replacement",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Cost2024 = [Cost Labor]+[Cost Material]+[Cost Overhead]",
              "VAR Replacement2024 = [Replacement Cost Labor]+[Replacement Cost Material]+[Replacement Cost Overhead]",
              "",
              "RETURN",
              "Cost2024-Replacement2024"
            ],
            "lineageTag": "f3155106-47ba-48aa-ae93-f1e3ab530376"
          },
          {
            "name": "2024Costvs2024Replacement%",
            "expression": [
              "",
              "VAR Cost2024 = [Cost Labor]+[Cost Material]+[Cost Overhead]",
              "VAR Replacement2024 = [Replacement Cost Labor]+[Replacement Cost Material]+[Replacement Cost Overhead]",
              "VAR CostMinusReplacement2024 = Cost2024-Replacement2024",
              "",
              "RETURN CostMinusReplacement2024/Cost2024"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "f0ef2563-504f-45fe-8b60-aec837603b0b"
          }
        ],
        "partitions": [
          {
            "name": "Calculation group",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Material Code Config",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a104d62-1e2c-418b-a85b-aa92bb50cfaa",
            "sourceColumn": "Product Category",
            "summarizeBy": "none"
          },
          {
            "name": "Product Class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d0a459f-2e5f-42cf-87d0-2401262177f7",
            "sourceColumn": "Product Class",
            "summarizeBy": "none"
          },
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aeefde8e-28ee-4571-8698-d45d945d13d7",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b074f7a1-52f6-410f-aa62-bcb6e35ae101",
            "sourceColumn": "Capacity",
            "summarizeBy": "sum"
          },
          {
            "name": "Material",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "73eff961-cd76-42fa-a15b-47a5f0fd3ab9",
            "sourceColumn": "Material",
            "summarizeBy": "none"
          },
          {
            "name": "Material Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0090bb70-b3c0-4c1c-8ebc-3169a165b2d2",
            "sourceColumn": "Material Description",
            "summarizeBy": "none"
          },
          {
            "name": "Model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87732baa-629f-4c45-b9d1-fcd904b55f47",
            "sourceColumn": "Model",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "631992ca-2e6d-4f64-86db-9bc2833cb2dc",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "12568bee-f1d0-4a56-b368-5bdaad064a8c",
        "partitions": [
          {
            "name": "Material Code Config",
            "mode": "import",
            "queryGroup": "Data Configs",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Material Mapping\"",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_07179c71-eae1-4574-9a32-16e5867a11f0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5bb8df2b-e844-45eb-b3ae-602741fc0fc5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "79c8bb24-b8d6-49f7-8c9d-79b6ca27808a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "07151b30-0349-4cc4-99fe-a1820bf3d7e3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "760429fc-2e04-465e-a3b6-2dcc990219de",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "710d7816-4924-4768-bed7-b4c62b8fb9dc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "17718658-6650-49a2-bd80-c5d90f0f50e9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c1261a3a-6d90-4a23-9769-d19d90ff6ef5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5adce42e-701f-468d-bc43-bb9ecd7572a7",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a8adae29-38dd-4641-a2d0-1c70452619b1",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "2e8e1d08-e728-4a9c-9dba-4a11454a3d68",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "68d424dc-7d19-48ca-a20a-4a2fe9b71217",
                "ordinal": 3
              }
            ],
            "lineageTag": "4195a040-b295-4b3f-8bda-a7b483fd6099"
          }
        ],
        "isHidden": true,
        "lineageTag": "0f015f01-0a30-44fb-8605-9b610b1856dc",
        "partitions": [
          {
            "name": "LocalDateTable_07179c71-eae1-4574-9a32-16e5867a11f0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Rolling Calendar Config'[Date])), 1, 1), Date(Year(MAX('Rolling Calendar Config'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Inventory Production Config",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Material",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fc795331-6116-47ce-bd00-a5c0a04832ed",
            "sourceColumn": "Material",
            "summarizeBy": "none"
          },
          {
            "name": "Material description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d162f7b-b08e-4c30-9bba-84bf30f0c3ea",
            "sourceColumn": "Material description",
            "summarizeBy": "none"
          },
          {
            "name": "Movement type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8f922a86-a79f-4968-9e23-9891a2f632e9",
            "sourceColumn": "Movement type",
            "summarizeBy": "sum"
          },
          {
            "name": "Qty in unit of entry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68a64b26-790f-475f-9968-3ccf502844c6",
            "sourceColumn": "Qty in unit of entry",
            "summarizeBy": "sum"
          },
          {
            "name": "Entry Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b09727b-3c1c-4bf3-9ac6-e16da21f5a06",
            "sourceColumn": "Entry Date",
            "summarizeBy": "none"
          },
          {
            "name": "Model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a0f421c-1878-442b-9353-0ae9b3779a07",
            "sourceColumn": "Model",
            "summarizeBy": "none"
          },
          {
            "name": "Product Class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebc499dd-dd24-4c1f-8a18-97caf574e055",
            "sourceColumn": "Product Class",
            "summarizeBy": "none"
          },
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5a9c016-77c8-4151-9401-72faf27ea814",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c3e99cee-8907-4a48-a81e-43d9ee952984",
        "partitions": [
          {
            "name": "Inventory Production Config",
            "mode": "import",
            "queryGroup": "Data Configs",
            "source": {
              "expression": [
                "let",
                "    Source = #\"Inventory Reference\",",
                "    #\"Merged Queries\" = Table.NestedJoin(Source, {\"Material\"}, #\"Material Mapping\", {\"Material\"}, \"Material Mapping\", JoinKind.LeftOuter),",
                "    #\"Expanded Material Mapping\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Material Mapping\", {\"Product Class\", \"Classification\", \"Model\"}, {\"Product Class\", \"Classification\", \"Model\"}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Expanded Material Mapping\",{\"Material\", \"Material description\", \"Movement type\", \"Qty in unit of entry\", \"Model\", \"Entry Date\"})",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimReplacement Cost",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d44089d-e3bf-457b-844a-751d48fa7978",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c4c6f78-c684-4f22-8cf7-4510db38bfaa",
            "sourceColumn": "Capacity",
            "summarizeBy": "none"
          },
          {
            "name": "Model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d7f1b57-4d4a-4353-a29f-31effd1ff43e",
            "sourceColumn": "Model",
            "summarizeBy": "none"
          },
          {
            "name": "Material Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4f1c3f8d-0f05-4884-8668-5337417c7147",
            "sourceColumn": "Material Code",
            "summarizeBy": "none"
          },
          {
            "name": "Decription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "317b73d3-3469-435b-a6af-f8b675ea1670",
            "sourceColumn": "Decription",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a64fa5df-8bd5-4009-b267-9a0e32fefe9c",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "2023 Standard Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cba26de7-4767-4172-bc64-f213f4761a85",
            "sourceColumn": "2023 Standard Cost",
            "summarizeBy": "none"
          },
          {
            "name": "2023 REPL @ ACT FX",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9c9611c8-55b2-4740-9a10-b2f032525232",
            "sourceColumn": "2023 REPL @ ACT FX",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "20bb9b6c-3e3c-4feb-9ee1-8e8b116beb59",
        "partitions": [
          {
            "name": "DimReplacement Cost",
            "mode": "import",
            "queryGroup": "Data Configs",
            "source": {
              "expression": [
                "let",
                "    Source = #\"2023 Retail & Replacement Cost (Temporary)\"",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}